#!/usr/bin/perl
#-----------------------------------------------------------------------------
#
#  Tirex Tile Rendering System
#
#  backends/mapserver
#
#  heavily based on WMS Backend by Jochen Topf
#
#-----------------------------------------------------------------------------
#  See Tirex::Backend::Mapserver for documentation.
#-----------------------------------------------------------------------------
#
#  Copyright (C) 2012  Sven Geggus <sven-osm@geggus.net>
#  
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; If not, see <http://www.gnu.org/licenses/>.
#
#-----------------------------------------------------------------------------

use strict;
use warnings;

use Tirex::Backend::Mapserver;

#-----------------------------------------------------------------------------

my $backend = Tirex::Backend::Mapserver->new();
$backend->main();

#-- THE END ------------------------------------------------------------------
