#!/usr/bin/perl
#-----------------------------------------------------------------------------
#
#  Tirex Tile Rendering System
#
#  munin/tirex-diskusage
#
#-----------------------------------------------------------------------------

use strict;
use warnings;

use Tirex::Munin::Tiledir::Diskusage;

#-----------------------------------------------------------------------------

my $config_file = $Tirex::TIREX_CONFIGFILE;
Tirex::Config::init($config_file);

#-----------------------------------------------------------------------------

my $map = 'default';
my @z   = ('0-9', 10 .. 17);

Tirex::Munin::Tiledir::Diskusage->new( map => $map, z => \@z )->do();


#-- THE END ------------------------------------------------------------------
