#!/usr/bin/perl
#-----------------------------------------------------------------------------
#
#  Tirex Tile Rendering System
#
#  munin/tirex-status-queued-requests.pl
#
#-----------------------------------------------------------------------------

use strict;
use warnings;

use Tirex::Munin::Status::QueuedRequests;

#-----------------------------------------------------------------------------

my $config_file = $Tirex::TIREX_CONFIGFILE;
Tirex::Config::init($config_file);

#-----------------------------------------------------------------------------

my @z = ('0-9', 10 .. 17);

Tirex::Munin::Status::QueuedRequests->new( z => \@z )->do();


#-- THE END ------------------------------------------------------------------
