#!/usr/bin/perl
#-----------------------------------------------------------------------------
#
#  Tirex Tile Rendering System
#
#  munin/tirex-status-requests-rendered.pl
#
#-----------------------------------------------------------------------------

use strict;
use warnings;

use Tirex::Munin::Status::RequestsRendered;

#-----------------------------------------------------------------------------

my $config_file = $Tirex::TIREX_CONFIGFILE;
Tirex::Config::init($config_file);

#-----------------------------------------------------------------------------

my $map = 'default';
my @z   = ('0-9', '10-12', '13-15', '16-17');

Tirex::Munin::Status::RequestsRendered->new( map => $map, z => \@z, per => 'minute' )->do();


#-- THE END ------------------------------------------------------------------
